language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - "8"
script:
  - yarn test
  - yarn build
  - cat dist/* | sha256sum | tee -a SHA256SUMS.txt
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - dist/binance-data-linux
    - dist/binance-data-macos
    - dist/binance-data-win.exe
    - SHA256SUMS.txt
  skip_cleanup: true
  on:
    tags: true
