version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
      - run: sha256sum dist/* | tee SHA256SUMS.txt
      - run: mv SHA256SUMS.txt dist
      - store_artifacts:
          path: dist
          destination: dist
